name: 'Collect build metrics'
description: 'Will collect build metrics and return as an array of objects'
branding:
  icon: bar-chart
  color: light-blue
inputs:
  send_to_dd:
    description: 'Boolean to send metrics to datadog'
    required: false
  datadog_url_location:
    description: 'eu or com depending on where your datadog endpoint is located (EU or US respectively). Required if no `send_to_dd` provided.'
    required: false
  save_to_fs:
    description: 'Boolean to save metrics to filesystem'
    required: false
  filename:
    description: 'The name of the file to save metrics with. Required if no `save_to_fs` provided.'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
