name: Testing build speed
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  GITHUB_TOKEN: ${{ secrets.USER_TOKEN }}

jobs:
  job1:
    runs-on: ubuntu-latest
    name: job1
    steps:
      - name: Extract branch name
        run: echo "::set-env name=APP_ENV::${GITHUB_REF#refs/heads/}"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print branch name
        run: echo $APP_ENV

  build-metrics:
    runs-on: ubuntu-latest
    name: collect metrics
    needs: job1
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Collect build metrics
        run: node dist/index.js

      - name: Upload to artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-metrics
          path: build-metrics.json
